name: dart_generic_lib
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:

  # ╔═══════════════════════════╗
  # ║          官方出品          ║
  # ╚═══════════════════════════╝
  intl: ^0.18.0 # [官方] 国际化 包含时间format
  http: ^0.13.4 # [官方]
  ansicolor: ^2.0.1
  stack_trace: ^1.10.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
